name: Auto Tag on Main Push

on:
  push:
    branches:
      - master

jobs:
  tag-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get date-based tag
        id: get_tag
        run: |
          TAG="v$(date +'%Y.%m.%d')"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Create and push tag
        env:
          TAG: ${{ steps.get_tag.outputs.tag }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag $TAG
          git push origin $TAG
