name: Auto Tag on Main Push

on:
  push:
    branches:
      - master

jobs:
  tag-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get date-based tag
        id: get_tag
        run: |
          TAG="v$(date +'%Y.%m.%d')"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Create and push tag
        env:
          TAG: ${{ steps.get_tag.outputs.tag }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists locally, deleting it"
            git tag -d "$TAG"
          fi

          if git ls-remote --tags origin | grep "refs/tags/$TAG$" >/dev/null 2>&1; then
            echo "Tag $TAG already exists remotely, deleting it"
            git push --delete origin "$TAG"
          fi

          git tag "$TAG"
          git push origin "$TAG"
