name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:

    runs-on: ubuntu-latest
    container: eclipse-temurin:21-jdk

    steps:
      - uses: actions/checkout@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # - name: Run Checks
      #   run: ./gradlew --stacktrace -PjavafxPlatform=linux

      # - name: Build Linux Files
      #   run: |
      #     ./gradlew -Pversion="${{ github.ref_name }}" -PjavafxPlatform=linux --stacktrace distZip

      - name: Build Windows Files
        run: |
          ./gradlew -Pversion="${{ github.ref_name }}" -PjavafxPlatform=win --stacktrace distZip

      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: true
          prerelease: true

      # - name: Get Artifact Paths
      #   id: artifact_paths
      #   run: |
      #     LINUX_ZIP=$(ls build/distributions/faf-moderator-client-*-linux.zip | head -n 1)
      #     LINUX_ZIP_NAME=$(basename $LINUX_ZIP)
      #     WINDOWS_ZIP=$(ls build/distributions/faf-moderator-client-*-win.zip | head -n 1)
      #     WINDOWS_ZIP_NAME=$(basename $WINDOWS_ZIP)
      #     echo ::set-output name=LINUX_ZIP::${LINUX_ZIP}
      #     echo ::set-output name=LINUX_ZIP_NAME::${LINUX_ZIP_NAME}
      #     echo ::set-output name=WINDOWS_ZIP::${WINDOWS_ZIP}
      #     echo ::set-output name=WINDOWS_ZIP_NAME::${WINDOWS_ZIP_NAME}

      - name: Upload Windows zip
        id: upload-zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/distributions/faf-moderator-client-*-win.zip
          asset_name: faf-moderator-client-${{ github.ref_name }}-win.zip
          asset_content_type: application/zip
