name: Release

on:
  workflow_run:
    workflows: ["Auto Tag on Main Push"]
    types:
      - completed

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_latest_tag.outputs.latest_tag }}
          release_name: ${{ steps.get_latest_tag.outputs.latest_tag }}
          draft: false
          prerelease: false

      - name: Build Windows Files
        uses: docker://eclipse-temurin:21-jdk
        with:
          entrypoint: /bin/bash
          args: -c "chmod +x ./gradlew && ./gradlew -Pversion=${{ steps.get_latest_tag.outputs.latest_tag }} -PjavafxPlatform=win --stacktrace distZip"

      - name: Find Windows zip file
        id: find_win_zip
        run: |
          FILE=$(ls build/distributions/faf-moderator-client-*-win.zip | head -n 1)
          echo "file=$FILE" >> $GITHUB_OUTPUT
          echo "zip_name=$(basename $FILE)" >> $GITHUB_OUTPUT

      - name: Upload Windows zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.find_win_zip.outputs.file }}
          asset_name: faf-moderator-client-${{ steps.get_latest_tag.outputs.latest_tag }}-win.zip
          asset_content_type: application/zip
